### ISSUE TITLE
[Suggestion] Static functions for buffers

### ISSUE THREAD

**Issue by jayands** [kawanet/int64-buffer#11]
Why not have the `Int64BE` class and friends have the static API to match the Node `Buffer` one? That way it could be a drop-in replacement for things like `Buffer.from` or `Buffer.alloc`. You can keep the old behavior, as you can still call `new Buffer(...)`, it's just deprecated due to clarity issues.

**Comment by kawanet** [comment]
`new Buffer()` is removed since issue #10 .

**Comment by kawanet** [comment]
It also supports no memory copy style as below:

```js
var buffer = Buffer.from([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]);
var big = new Uint64BE(buffer, 8);
console.log(big.toString(16)); // "90a0b0c0d0e0f10"
```

It still creates an new object though.
I'm not sure what you mean for "static API".
You'd mean something like below?

```js
var buffer = Buffer.from([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]);
console.log(Uint64BE.toString(buffer, 8, 16)); // "90a0b0c0d0e0f10"
```
