### ISSUE TITLE
License confirmation

### ISSUE THREAD

**Issue by TC01** [kawanet/int64-buffer#5]
Hi,

I'm packaging int64-buffer (as it's a dependency of a web application I'd like to make available) for Fedora, and I [was asked during the review process](https://bugzilla.redhat.com/show_bug.cgi?id=1397620) to confirm the licensing, and namely that all code/contents is indeed under the MIT license.

**Comment by kawanet** [comment]
Yes, all code/contents is indeed under the MIT license.
It requires no dependency modules which may apply another license.

https://github.com/kawanet/int64-buffer/blob/master/package.json has the license field to indicate it on npm manner.

https://github.com/kawanet/int64-buffer/blob/master/LICENSE is the MIT license file.

I have no idea to pass RedHat's license checks.
Any pull requests to pass it would be appreciated.
Thank you for reviewing it, anyway.

**Comment by TC01** [comment]
Thanks for the quick response! This confirmation from you was all that was necessary. :)
