### ISSUE TITLE
Question. Reading and Writing int64-buffer values to a Buffer

### ISSUE THREAD

**Issue by kirangangineni** [kawanet/int64-buffer#6]
Hi ,
I am wanted to Read and write 64 bit value to a Buffer. I am able to write the values to the buffer but while reading back getting truncation issue. What is best way to read and write 64 bit values to buffer. 

var Int64BE = require("int64-buffer").Int64BE
var d = new Int64BE(9223372036854775807);
 let buf = new Buffer(8);
 buf = d.toBuffer();

var e = new Int64BE(buf);
console.log(e.toNumber())

I get the result of e.toNumber() as  -9223372036854776000

**Comment by kawanet** [comment]
If you already have an Buffer instance, call the constructor with existing buffer and address offset: `new Int64BE(buffer, offset, number)`

```js
var Int64BE = require("int64-buffer").Int64BE
let buf = new Buffer(8);
var d = new Int64BE(buf, 0, 9223372036854775807);
```

If you need the exact precision of the value, use a String instead of a Number which only has 53bit precision on our JavaScript world.

```js
var e = new Int64BE("9223372036854775807");
console.log(e.toString()); // => "9223372036854775807"
```
