### ISSUE TITLE
New Versions?

### ISSUE THREAD

**Issue by jayands** [kawanet/int64-buffer#9]
The version on [NPMJS.com][npmjs] is very much out of sync with the version listed in `package.json`. It needs to be updated.

[npmjs]: https://www.npmjs.com/package/int64-buffer

**Comment by kawanet** [comment]
`int64-buffer.js` itself is not changed since 2016.
The current master branch has tests targeted for node version 10 on Travis CI.
The updating process is suspended for while since I was busy.
I'll resume it to release it to npmjs, thanks!

**Comment by kawanet** [comment]
Published 🎉 

https://www.npmjs.com/package/int64-buffer
